apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: serverless-rolebinding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: serverless-role
subjects:
- kind: ServiceAccount
  name: serverless-serviceaccount
  namespace: default
