# permissions for end users to view serverlesses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: serverless-viewer-role
rules:
- apiGroups:
  - serverless.devs.serverless.domain
  resources:
  - serverlesses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - serverless.devs.serverless.domain
  resources:
  - serverlesses/status
  verbs:
  - get
