# permissions for end users to edit serverlesses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: serverless-editor-role
rules:
- apiGroups:
  - serverless.devs.serverless.domain
  resources:
  - serverlesses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - serverless.devs.serverless.domain
  resources:
  - serverlesses/status
  verbs:
  - get
